### ISSUE TITLE
gsl-shell-gui.exe  - breaks if mouse used above command line

### ISSUE THREAD

**Issue by Gavin-Holt** [franko/gsl-shell#36]
Hi,

Returning to update my installation of GSL-Shell for Windows ( gsl-shell-windows-x86.zip
4.29 MB 15 Apr 2022 ) the GUI shell is not working as expected. 

- I can run commands and plot demo graphs.
- If I use my mouse to click or select anywhere above the active command line the application becomes unusable.
- The escape key does not return control to the active command line as discussed in issue #16 .

I have tested on Windows 8.1 and windows 10. 

Kind Regards Gavin Holt

**Comment by franko** [comment]
Thank you for reporting the problem and for reminding me about the escape key, I will try to fix these problems.

**Comment by franko** [comment]
Just to be sure, when you say:

> f I use my mouse to click or select anywhere above the active command line the application becomes unusable.

how the application is unusable ? My guess is that if you press some keys nothing happens but the application remains responsive.

**Comment by Gavin-Holt** [comment]
Hi,

When I click anywhere above the active command line I loose any ability to
enter keystrokes. The is a faint dead cursor at the command line and a
second dead cursor in the text above. I have to close the application and
restart.

Kr Gavin Holt

**Comment by franko** [comment]
Normally solved with the new 2.3.4 release:

https://github.com/franko/gsl-shell/releases/tag/v2.3.4

Please check if everything looks fine for you. If yes we can close this issue.

**Comment by Gavin-Holt** [comment]
Hi,

The new version has solved this problem. Esc work nicely to bring me back
to a functional command line.

Many thanks

KR Gavi
