### ISSUE TITLE
README.md links broken

### ISSUE THREAD

**Issue by shmuz** [franko/gsl-shell#40]
In the Build Instructions there are 3 links. None of them works.
Each one opens a page with text "Non-Image content-type returned".

**Comment by franko** [comment]
Thank you for pointing out the problem. I have fixed the README but I have also modified the build process to be more easy: now the FOX toolkit will be automatically downloaded and built as a subproject.

This means that now GSL Shell can be compiled on Linux by just installing the standard dev packages xorg-dev and pkg-config besides, of course Meson and gcc.

**Comment by shmuz** [comment]
Thank you!
